name: Setup and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
#    - name: Setup wasmer and wapm (macos)
#      run: |
#        brew install wasmer
#        brew install wapm
    - name: Setup Wasmer
      uses: wasmerio/setup-wasmer@v1
    - name: install python wasm
      # pipe "y" into wapm install to confirm key ssh key
      run: |
        echo y | wapm install python/python
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
    - name: Run Example Sandbox
      run: |
        python example_sandbox.py
