name: Setup and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          #- "3.11" <- failing
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Wasmer
      uses: wasmerio/setup-wasmer@v3
    - name: install python wasm
      # pipe "y" into wapm install to confirm key ssh key
      run: |
        echo y | wapm install python
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: "${{ matrix.python }}"
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
    - name: Run Example Sandbox
      run: |
        python example_sandbox.py
